# Generated by Django 3.1.5 on 2021-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_info_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_info',
            name='cost',
            field=models.IntegerField(default=5),
        ),
    ]
